baseURL: "https://cristianriverag.netlify.app/"
languageCode: "en-us"
title: "Cristian Rivera G."
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Cristian R."
  description: Mi página personal
  # staticPath: ""  # The path to serve the static files from
  favicon: "/euler-diagram.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor: "#070707"
  #   secondaryTextColor: "#757575"
  #   backgroundColor: "#B2B5E0"
  #   secondaryBackgroundColor: "#FFD43A"
  #   primaryColor: "#F1E0AC"
  #   secondaryColor: "#96C2DB"

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "Cristian Rivera" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Buscar en blog"
    stickyNavBar:
      enable : true
      showOnScrollUp : false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: ""
    title: "¡Bienvenid@!"
    subtitle: "Gracias por visitar mi página"
    content: "Este es un espacio dedicado a compartir mis intereses relacionados con la tecnonlogía y algo más."
    image: /images/Captura.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Proyectos"
      url: "#projects"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/riveracrist
        - icon: fab fa-x-twitter
          url: https://x.com/CrGoo7
        - icon: fab fa-facebook
          url: https://www.facebook.com/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "Conóceme"
    image: "/images/microchip.png"
    content: |-
      Aprendiz de Ingeniería en Telecomunicaciones y aprendiz de Análisis y Desarrollo de Software, con una curiosidad por la ciencia de datos y las tecnologías de la información y las comunicaciones (TIC).
      
      Tengo un interés particular en el aprendizaje de lenguajes de programación como R y Python, debido a su aplicabilidad en el análisis y visualización de información. Deseo adquirir un conocimiento sólido en la gestión de bases de datos utilizando SQL, comprender cómo se estructuran, almacenan y consultan los datos de forma eficiente.
      
      Paralelamente, me motiva explorar el campo de la electrónica, donde utilizo plataformas como Arduino y Raspberry Pi para comprender los principios básicos del hardware, su conexión con el desarrollo de soluciones tecnológicas y la automatización.
      
      
    skills:
      enable: true
      title: "Otros Intereses:"
      items:
        - "Astronomía"
        - "Cloud Computing"
        - "Estadística"
        - "Historia"
        - "Inteligencia Artificial"
        - "Mascotas"
        - "Música"
        - "Video Juegos"
        
  # Experience
  experience:
    enable: true
    title: "Aprendiendo sobre"
    items:
      - job: "Bases de Datos"
        company: "Oracle Academy"
        companyUrl: "https://www.netacad.com/"
        #date: "Ago 2024"
        featuredLink:
          enable: false
          name: "Contenido"
          url: "https://academy.oracle.com/pages/coursedescription/Oracle%20Academy%20Database%20Design%20Course%20Description.pdf"
        info:
          enable: false
        content: |
        
          - [**Database Design**](https://academy.oracle.com/pages/coursedescription/Oracle%20Academy%20Database%20Design%20Course%20Description.pdf).
          
          <img src="/images/oracle.png" alt="drawing" style="width:130px;"/>

      - job: "Python"
        company: "Cisco Networking Academy"
        companyUrl: "https://www.netacad.com/"
        #date: "Dic 2024"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          
          - [**Python Essentials 1**](https://www.netacad.com/courses/python-essentials-1?courseLang=en-US).
          
          
          - [**Python Essentials 2**](https://www.netacad.com/courses/python-essentials-2?courseLang=en-US).
          
          <img src="/images/python-essentials-1.png" alt="drawing" style="width:130px;"/>
          <img src="/images/python-essentials-2.png" alt="drawing" style="width:130px;"/>

      - job: "Google Cloud"
        company: "Coursera - Google"
        companyUrl: "https://www.coursera.org/"
        #date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          
          - [**Google Cloud Fundamentals Core Infrastructure**](https://www.coursera.org/account/accomplishments/verify/K34OW9CJ58MP).
          
          
          - [**Architecting with Google Kubernets Engine**](https://www.coursera.org/account/accomplishments/verify/6X8ZTZISL4HQ).
          
          
          - [**Data Analysis with R Programming**](https://coursera.org/share/519a1b54037a183c80b2450cf99e5a80)
          
          <img src="/images/coursera.png" alt="drawing" style="width:130px;"/>
          <img src="/images/kubernetsMinTIC.png" alt="drawing" style="width:130px;"/>
          <img src="/images/coursera.png" alt="drawing" style="width:130px;"/>
          

      - job: "Desarrollo de Software"
        company: "SENA"
        companyUrl: "https://oferta.senasofiaplus.edu.co/sofia-oferta/buscar-oferta-educativa.html?radio=opcion202&buscador_texto=&ffv=-1&ciudad=Ej%3A+Cali%2C+Cartagena&campoEmpresa=&nfct=-1"
        #date: "June 2017 - Nov 2019"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
        content: |
          
          - Bases de Datos: generalidades y sistemas de gestión.
          - Construcción Bases de Datos con MySQL.
          - Variables y Estructuras de Control en Python.
          - Análisis Exploratorio de Datos con Python.
          - Estructura del Lenguaje de Programación C++ (Nivel I).
      # 
      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    title: "Educación"
    index: false
    items:
      - title: "Ingeniería de Telecomunicaciones"
        school:
          name: "Universidad de Antioquia, Medellín"
          url: "https://www.udea.edu.co/"
        date: "2024 - En curso"
        #GPA: "3.8 out of 5.0"
        content: |-
          
          Actividades Extracurriculares:
            - Master Power BI Microsoft - Intelligent Training.
            - Master class Tu Carrera en la Nube - MinTIC, Google.
            - Taller Aulas de Inovación - Facultad de Ingeniería, Comisión de Regulación de Comunicaciones.
      - title: "Tecnología en Análisis y Desarrollo de Software (ADSO)"
        school: 
          name: "Centro Agroempresarial y Minero - SENA, Regional Bolívar"
          url: "https://www.sena.edu.co/es-co/Paginas/default.aspx"
        date: "2023 - En curso"
        #GPA: "3.9 out of 5.0"
        content: |-
          
          Actividades Extracurriculares:
            - Vocero de la ficha de ADSO
            - Representante de estudiantes modalidad virtual.
            - Encuentro Zonal de liderazgo 2024 Neiva, Huila.
        featuredLink:
          enable: true
          name: "Proyecto Página Web ADSO"
          url: "https://example.com"
      - title: "Ingeniería de Control"
        school:
          name: "Universidad Nacional de Colombia, Medellín"
          url: "https://unal.edu.co/"
        date: "2015 - No completado"
        #GPA: "3.8 out of 5.0"
        content: |-
          Actividades Extracurriculares:
            - Auxiliar de Docencia Laboratorio de Geotecnia y Pavimentos.
            - Auxiliar Administrativo.
            - [Semillero en Ciencia de Datos R y Python](https://semillerorpy.netlify.app/).
            
            
        # Cursos Aprobados:
        #   - Geometría Vectorial y Analítica. 
        #   - Álgebra Lineal.
        #   - Cálculo Diferencial.
        #   - Calculo Integral.
        #   - Estadística.
        #   - Física Mecánica.
        #   - Electricidad y Magnetismo.
        #   - Análisis de Circuitos Eléctricos.
        #   - Instrumentación.
      
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   title: "Cursos Complementarios"
  #   items:
  #     - title: Python Essentials 1
  #       #content: Variables, operadores aritméticos, tipos de datos, operadores lógicos, condicionales (if, elif, else), strings, bucles (for, while), tuplas, listas, diccionarios, conjuntos, manejo de excepciones.
  #       url: https://www.netacad.com/courses/python-essentials-1?courseLang=en-US
  #       image: /images/python-essentials-1.png
  #     - title: Python Essentials 2
  #       url: https://www.netacad.com/courses/python-essentials-2?courseLang=en-US
  #       #content: Módulos, paquetes, instalar paquetes, fundamentos POO (propiedades, métodos, herencia), excepciones, manejo de archivos, módulo os, módulo datetime, modulo calendar. 
  #       image: /images/python-essentials-2.png
  #     - title: Database Design
  #       #content: Modelos conceptuales y físicos, entidades, instancias, atributos, identificadores, modelado de relación de entidades, ERD, diagamas de matriz, super tipos, subtipos, documentación reglas de negocio, relaciones transferibles, UID (artificlaes, compuestos, secundarios), arcos, jerarquías, modelado recursivo, modelado de datos históricos.
  #       url: https://academy.oracle.com/pages/coursedescription/Oracle%20Academy%20Database%20Design%20Course%20Description.pdf
  #       image: /images/oracle.png
  #     - title: Google Cloud Fundamentals Core Infrastructure en Español
  #       url: https://www.coursera.org/account/accomplishments/verify/K34OW9CJ58MP
  #       image: /images/coursera.png
  #       #content: We are developed a product which can help others.
  #     - title: Architecting with Google Kubernetes Engine, Foundations en Español
  #       #content: Contributed to a open source project.
  #       url: https://www.coursera.org/account/accomplishments/verify/6X8ZTZISL4HQ
  #       image: /images/kubernetsMinTIC.png

  # Projects
  projects:
    enable: true
    title: "Proyectos Personales"
    items:
      - title: Sitio Web ADSO 
        content: Página Web creada con Quarto para la tecnología de Análisis y Desarrollo de Software del SENA.
        image: /images/projects/sitioweb.png
        featured:
          name: Link
          link: https://riveracrist.github.io/
        badges:
          - "Quarto"
          - "Markdown"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Tablero de Datos
        content: Plantilla de un tablero de datos estático, creado con la biblioteca Flexdashboard de R.
        image: /images/projects/tablero_black.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/986419
        badges:
          - "Flexdashboard"
          - "Markdown"
          - "R"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      - title: Tablero de Datos con Arduino
        content: Tablero de datos que visualiza los datos capturados con sensores programados con Arduino.
        image: /images/projects/tableroarduino.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/1138902
        badges:
          - "Arduino"
          - "Flexdashboard"
          - "R"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2
            
      - title: R + RStudio + MySQL
        content: Documento Markdown que muestra cómo conectarse a una base de datos MySQL desde RStudio para realizar consultas y gráficos.
        image: /images/projects/rstuio_mysql.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/1069870
        badges:
          - "MySQL"
          - "ggplot2"
          - "Markdown"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      - title: Análisis Exploratorio Covid-19 Colombia
        content: Breve análisis descriptivo con R haciendo uso de datos abiertos del gobierno de Colombia.
        image: /images/projects/covid.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/691934
        badges:
          - "Arduino"
          - "Flexdashboard"
          - "R"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2
            
      - title: Ejemplo de cuestonario con Paquete de R learnr
        content: Herramienta para crear tutoriales interactivos o cuestionarios que se pueden publicar en shinyapps.
        image: /images/projects/learnr.png
        featured:
          name: Link
          link: https://m8juuc-riveracrist.shinyapps.io/Circuitos/
        badges:
          - "learnr"
          - "Educación"
          - "R"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  # contact:
  #   enable: true
  #   title: "Contáctame"
  #   content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
  #   email: gurusabarisha@gmail.com
  #   btnName: Mail me
  #   formspree:
  #     enable: true # `contact.email` value will be ignored
  #     formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
  #     emailCaption: "Enter your email address"
  #     messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Últimas Publicaciones
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      #linkedin: https://linkedin.com
      twitter: https://twitter.com
      #instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "mins. de lectura"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Leer"
    toc: "Tabla de Contenido"
    copyright: "Todos los derechos reservados"
    pageNotFound: "Página no encontrada"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
